pubspec.yaml
lib/
android/
ios/
name: Build Future Trading APK

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: future_trading_with_firebase_plus_guide  # 👈 your folder name

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: FutureTrading-APK
          path: future_trading_with_firebase_plus_guide/build/app/outputs/flutter-apk/app-release.apk
